### ISSUE TITLE
Import of the 2-0.uasset doesn't work

### ISSUE THREAD

**Issue by nicwhites** [kromond/AnimToTextureHelpers#11]
When I download and attempt to manually place the 2-0 into my project directory, it doesn't show up at all. I don't get any errors saying why. I will attempt to look further, but I wanted to bring it to y'alls attention.

**Comment by kromond** [comment]
be sure to clone the repo and don't use the zip.  There is a note on the ReadMe

**Comment by nicwhites** [comment]
I read the README and have downloaded the files individually and also cloned the repo. Both ways result the exact same

**Comment by kromond** [comment]
Ok thanks for letting me know.  And just to confirm, you are trying this in UE 5.2 right?

**Comment by Kapoff** [comment]
Similar issue, the 2-0.uasset is not detected. 
working in 5.3, so that might be the issue. 
Also, probably 5.3 related, the AnimToTextureMaterialParamNames struct that is used in the VAT_Utils seems to be missing. 
I managed to open the 2-0 in an older UE version, and realised that you replaced a bunch of those struc based nodes with literals. 
So I'm trying to fix the VAT_Utils that I still have in the work project by referencing the new 2-0.

**Comment by JDadders** [comment]
@Kapoff if you manage to fix this for 5.3, could you submit a pull request please? That'd be much appreciated, thanks.

**Comment by gabrieljreed** [comment]
I have the same issue - not showing up in 5.3. Seems to work fine in 5.2.

**Comment by thehyenaman** [comment]
It shows up when I rename the folder the blueprint is in from the engine. But it doesn't work for 5.3 regardless, if anyone has a fix please point me in the right direction so I can hack at it at least.

**Comment by Majorek87** [comment]
doesn't work on 5.3 :/ Name structure in Vat Utils are missing, compile error

**Comment by macalbert05** [comment]
there is an error that in 5.2 when i bake it will not create a material instance

**Comment by tomaaron** [comment]
@thehyenaman check out my pr https://github.com/kromond/AnimToTextureHelpers/pull/14 It's for 5.4.3

**Comment by Mann763** [comment]
> @thehyenaman check out my pr #14 It's for 5.4.3

cant find the files i am able to only download old files.

**Comment by McHearty** [comment]
> @thehyenaman check out my pr #14 It's for 5.4.3

I'm still seeing the same missing struct in your PR, can you explain what you did/how to replicate?
