### ISSUE TITLE
Cannot run in UE 5.1

### ISSUE THREAD

**Issue by bailehang** [kromond/AnimToTextureHelpers#3]
Hi,

First of all thank you for showing it on video, but after two months the uassert would not be loaded correctly by the UE5.1
Please support the latest 5.1.1 version (83e2ae9b7ca36daf5f37b9b0115bea0864fcdcef) or provide a running engine version, I'll compile a working version myself. 

Thanks,
Clark

**Comment by bailehang** [comment]
![image](https://user-images.githubusercontent.com/7373218/227099821-226f2059-bf71-4019-b2d2-329dff879baf.png)
Because you can't download 5.1 from the official precompiled version, only 5.1.1, I confirm that this version is not working, probably due to the resource's object version limitations can not be loaded in properly.

Can you show your working git commit version(SHA) of the ue engine?

It doesn't matter if it doesn't. I've found the key code in the engine.

Thanks

**Comment by guiqian** [comment]
@bailehang i get wrong uasset file too. this file just 1 kb

**Comment by bailehang** [comment]
![image](https://user-images.githubusercontent.com/7373218/227424873-c35be1b2-8a45-4f29-a0e3-1050906173e4.png)
@guiqian 

I have seen the author's blueprint and it is working fine, I will close the issue, but still hope the author will support others to 5.1.1 or even 5.2, because the tool  is easy to use.

**Comment by guiqian** [comment]
@bailehang hello，can you tell me how to download uasset? thanks
![图片](https://user-images.githubusercontent.com/5927687/227434052-e1738e98-2abe-4521-8d00-4535da61ffd7.png)

**Comment by bailehang** [comment]
> I don't know why you download file error, directly download the zip package is always right.

**Comment by guiqian** [comment]
@bailehang i get right file, sorry. i closed my issue
