### ISSUE TITLE
5.2 compatibility 

### ISSUE THREAD

**Issue by Pamavoc** [kromond/AnimToTextureHelpers#6]
Hello, 

Some methods seems to be removed in Unreal 5.2. It breaks the way the GUI works.

What I noted inside EUW_VAT_UTILS : 

- AnimToTextureMaterialParamNames vanished.
- in CreateDataAsset function BonePrecision is not a variable + the Enum linked to it does not exist anymore.
- in BakeData function, UpdateMaterialLayerFunction is unknown.
- UpdateMaterialInstanceFromDataAsset lacks the AnimToTextureMaterialParamNames parameter.

That's it. Thanks in advance if you could look into it !! @kromond

**Comment by juaxix** [comment]
![image](https://github.com/kromond/AnimToTextureHelpers/assets/996806/b5865855-445b-42ed-b79d-203963a897a1)
yea, just updated and I see the issues, I didnt take a look to the solution but if you are going to fix it that would be nice :)

**Comment by kromond** [comment]
Sorry but I don't expect to be able to look into this anytime soon.  As noted, I offered these things without support.  Check the comments on the YT video, I saw some clues go by on how to fix
