### ISSUE TITLE
Unreal  5.2 - Issue

### ISSUE THREAD

**Issue by tyn7mau** [kromond/AnimToTextureHelpers#9]
![image](https://github.com/kromond/AnimToTextureHelpers/assets/77381744/87e8abbc-0a56-43d0-8efb-d0dbd5b859f7)

**Comment by AlexandrePoisson** [comment]
Indeed, unreal removed some node in 5.2 & 5.3 that Kromond was using.
Bad things is that Blueprints are completely broken.
Maybe you want to look at the example provided  in the plugin section :
![image](https://github.com/kromond/AnimToTextureHelpers/assets/13329302/dcf32338-5d23-4fdd-80af-bc4f0261add3)

**Comment by kromond** [comment]
a user has made a PR with a 5.2 update which was merged on main
